package com.froso.ufp.model;

public enum DiffRemark {
    NO_CHANGE,
    REALIZED_BUT_NOT_EXPECTED,

    MAJOR_CONSECUTIVITY_BREAK,
    MINOR_CONSECUTIVITY_BREAK,
    PATCH_CONSECUTIVITY_BREAK,

    MAJOR_JUMP_BACKWARDS_BREAK,
    MINOR_JUMP_BACKWARDS_BREAK,
    PATCH_JUMP_BACKWARDS_BREAK


}
